<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\NonTeachingStaff;
use App\Models\School;

class NonTeachingStaffSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Membuat 25 pegawai non guru manual, didistribusikan ke 6 sekolah
     */
    public function run(): void
    {
        $schools = School::pluck('id')->all();
        if (empty($schools)) {
            return;
        }

        $staffs = [
            [
                'school_id' => null,
                'full_name' => 'Dewi Safitri',
                'nip_nik' => '198501012010012001',
                'nuptk' => '198501012010012001',
                'birth_place' => 'Pematang Siantar',
                'birth_date' => '1985-01-01',
                'gender' => 'Perempuan',
                'religion' => 'Islam',
                'address' => 'Jl. Merdeka No. 10, Pematang Siantar',
                'staff_type' => 'Tata Usaha',
                'position' => 'Kepala TU',
                'education_level' => 'S1',
                'education_major' => 'Administrasi Pendidikan',
                'employment_status' => 'PNS',
                'rank' => 'III/c',
                'tmt' => '2010-01-01',
                'status' => 'Aktif'
            ],
            [
                'school_id' => null,
                'full_name' => 'Rina Marlina',
                'nip_nik' => '198601012010012002',
                'nuptk' => '198601012010012002',
                'birth_place' => 'Medan',
                'birth_date' => '1986-02-01',
                'gender' => 'Perempuan',
                'religion' => 'Islam',
                'address' => 'Jl. Merdeka No. 11, Pematang Siantar',
                'staff_type' => 'Tata Usaha',
                'position' => 'Staf TU',
                'education_level' => 'S1',
                'education_major' => 'Administrasi Pendidikan',
                'employment_status' => 'PNS',
                'rank' => 'III/b',
                'tmt' => '2011-01-01',
                'status' => 'Aktif'
            ],
            [
                'school_id' => null,
                'full_name' => 'Andi Pratama',
                'nip_nik' => '198701012010012003',
                'nuptk' => '198701012010012003',
                'birth_place' => 'Pematang Siantar',
                'birth_date' => '1987-03-01',
                'gender' => 'Laki-laki',
                'religion' => 'Islam',
                'address' => 'Jl. Merdeka No. 12, Pematang Siantar',
                'staff_type' => 'Keamanan',
                'position' => 'Satpam',
                'education_level' => 'SMA/SMK',
                'education_major' => 'IPS',
                'employment_status' => 'Honorer',
                'rank' => null,
                'tmt' => '2012-01-01',
                'status' => 'Aktif'
            ],
            [
                'school_id' => null,
                'full_name' => 'Budi Santoso',
                'nip_nik' => '198801012010012004',
                'nuptk' => '198801012010012004',
                'birth_place' => 'Medan',
                'birth_date' => '1988-04-01',
                'gender' => 'Laki-laki',
                'religion' => 'Islam',
                'address' => 'Jl. Merdeka No. 13, Pematang Siantar',
                'staff_type' => 'Kebersihan',
                'position' => 'Petugas Kebersihan',
                'education_level' => 'SMA/SMK',
                'education_major' => 'IPA',
                'employment_status' => 'Honorer',
                'rank' => null,
                'tmt' => '2013-01-01',
                'status' => 'Aktif'
            ],
            [
                'school_id' => null,
                'full_name' => 'Siti Aminah',
                'nip_nik' => '198901012010012005',
                'nuptk' => '198901012010012005',
                'birth_place' => 'Pematang Siantar',
                'birth_date' => '1989-05-01',
                'gender' => 'Perempuan',
                'religion' => 'Islam',
                'address' => 'Jl. Merdeka No. 14, Pematang Siantar',
                'staff_type' => 'Perpustakaan',
                'position' => 'Pustakawan',
                'education_level' => 'S1',
                'education_major' => 'Ilmu Perpustakaan',
                'employment_status' => 'PNS',
                'rank' => 'III/a',
                'tmt' => '2014-01-01',
                'status' => 'Aktif'
            ],
            [
                'school_id' => null,
                'full_name' => 'Rudi Hartono',
                'nip_nik' => '198601012010011001',
                'nuptk' => '198601012010011001',
                'birth_place' => 'Medan',
                'birth_date' => '1986-01-01',
                'gender' => 'Laki-laki',
                'religion' => 'Islam',
                'address' => 'Jl. Sudirman No. 15, Pematang Siantar',
                'staff_type' => 'Laboratorium',
                'position' => 'Kepala Lab IPA',
                'education_level' => 'S1',
                'education_major' => 'Pendidikan IPA',
                'employment_status' => 'PNS',
                'rank' => 'III/b',
                'tmt' => '2010-01-01',
                'status' => 'Aktif'
            ],
            [
                'school_id' => null,
                'full_name' => 'Dewi Anggraini',
                'nip_nik' => '199001012010011002',
                'nuptk' => '199001012010011002',
                'birth_place' => 'Pematang Siantar',
                'birth_date' => '1990-02-01',
                'gender' => 'Perempuan',
                'religion' => 'Islam',
                'address' => 'Jl. Sudirman No. 16, Pematang Siantar',
                'staff_type' => 'Laboratorium',
                'position' => 'Staf Lab IPA',
                'education_level' => 'S1',
                'education_major' => 'Pendidikan IPA',
                'employment_status' => 'PNS',
                'rank' => 'III/a',
                'tmt' => '2011-01-01',
                'status' => 'Aktif'
            ],
            [
                'school_id' => null,
                'full_name' => 'Andi Wijaya',
                'nip_nik' => '199101012010011003',
                'nuptk' => '199101012010011003',
                'birth_place' => 'Medan',
                'birth_date' => '1991-03-01',
                'gender' => 'Laki-laki',
                'religion' => 'Islam',
                'address' => 'Jl. Sudirman No. 17, Pematang Siantar',
                'staff_type' => 'Keamanan',
                'position' => 'Satpam',
                'education_level' => 'SMA/SMK',
                'education_major' => 'IPS',
                'employment_status' => 'Honorer',
                'rank' => null,
                'tmt' => '2012-01-01',
                'status' => 'Aktif'
            ],
            [
                'school_id' => null,
                'full_name' => 'Budi Prakoso',
                'nip_nik' => '199201012010011004',
                'nuptk' => '199201012010011004',
                'birth_place' => 'Pematang Siantar',
                'birth_date' => '1992-04-01',
                'gender' => 'Laki-laki',
                'religion' => 'Islam',
                'address' => 'Jl. Sudirman No. 18, Pematang Siantar',
                'staff_type' => 'Kebersihan',
                'position' => 'Petugas Kebersihan',
                'education_level' => 'SMA/SMK',
                'education_major' => 'IPA',
                'employment_status' => 'Honorer',
                'rank' => null,
                'tmt' => '2013-01-01',
                'status' => 'Aktif'
            ],
            [
                'school_id' => null,
                'full_name' => 'Siti Nurhaliza',
                'nip_nik' => '199301012010011005',
                'nuptk' => '199301012010011005',
                'birth_place' => 'Medan',
                'birth_date' => '1993-05-01',
                'gender' => 'Perempuan',
                'religion' => 'Islam',
                'address' => 'Jl. Sudirman No. 19, Pematang Siantar',
                'staff_type' => 'Perpustakaan',
                'position' => 'Pustakawan',
                'education_level' => 'S1',
                'education_major' => 'Ilmu Perpustakaan',
                'employment_status' => 'PNS',
                'rank' => 'III/a',
                'tmt' => '2014-01-01',
                'status' => 'Aktif'
            ],
            [
                'school_id' => null,
                'full_name' => 'Ahmad Fauzi',
                'nip_nik' => '198701012010011002',
                'nuptk' => '198701012010011002',
                'birth_place' => 'Pematang Siantar',
                'birth_date' => '1987-01-01',
                'gender' => 'Laki-laki',
                'religion' => 'Islam',
                'address' => 'Jl. Diponegoro No. 20, Pematang Siantar',
                'staff_type' => 'Perpustakaan',
                'position' => 'Kepala Perpustakaan',
                'education_level' => 'S1',
                'education_major' => 'Ilmu Perpustakaan',
                'employment_status' => 'PNS',
                'rank' => 'III/b',
                'tmt' => '2010-01-01',
                'status' => 'Aktif'
            ],
            [
                'school_id' => null,
                'full_name' => 'Dewi Sartika',
                'nip_nik' => '199401012010011003',
                'nuptk' => '199401012010011003',
                'birth_place' => 'Medan',
                'birth_date' => '1994-02-01',
                'gender' => 'Perempuan',
                'religion' => 'Islam',
                'address' => 'Jl. Diponegoro No. 21, Pematang Siantar',
                'staff_type' => 'Perpustakaan',
                'position' => 'Staf Perpustakaan',
                'education_level' => 'S1',
                'education_major' => 'Ilmu Perpustakaan',
                'employment_status' => 'PNS',
                'rank' => 'III/a',
                'tmt' => '2011-01-01',
                'status' => 'Aktif'
            ],
            [
                'school_id' => null,
                'full_name' => 'Andi Simbolon',
                'nip_nik' => '199501012010011004',
                'nuptk' => '199501012010011004',
                'birth_place' => 'Pematang Siantar',
                'birth_date' => '1995-03-01',
                'gender' => 'Laki-laki',
                'religion' => 'Islam',
                'address' => 'Jl. Diponegoro No. 22, Pematang Siantar',
                'staff_type' => 'Keamanan',
                'position' => 'Satpam',
                'education_level' => 'SMA/SMK',
                'education_major' => 'IPS',
                'employment_status' => 'Honorer',
                'rank' => null,
                'tmt' => '2012-01-01',
                'status' => 'Aktif'
            ],
            [
                'school_id' => null,
                'full_name' => 'Budi Simanjuntak',
                'nip_nik' => '199601012010011005',
                'nuptk' => '199601012010011005',
                'birth_place' => 'Medan',
                'birth_date' => '1996-04-01',
                'gender' => 'Laki-laki',
                'religion' => 'Islam',
                'address' => 'Jl. Diponegoro No. 23, Pematang Siantar',
                'staff_type' => 'Kebersihan',
                'position' => 'Petugas Kebersihan',
                'education_level' => 'SMA/SMK',
                'education_major' => 'IPA',
                'employment_status' => 'Honorer',
                'rank' => null,
                'tmt' => '2013-01-01',
                'status' => 'Aktif'
            ],
            [
                'school_id' => null,
                'full_name' => 'Lina Marlina',
                'nip_nik' => '199701012010012001',
                'nuptk' => '199701012010012001',
                'birth_place' => 'Pematang Siantar',
                'birth_date' => '1997-01-01',
                'gender' => 'Perempuan',
                'religion' => 'Islam',
                'address' => 'Jl. Sisingamangaraja No. 12, Pematang Siantar',
                'staff_type' => 'Tata Usaha',
                'position' => 'Staf TU',
                'education_level' => 'S1',
                'education_major' => 'Administrasi Pendidikan',
                'employment_status' => 'PNS',
                'rank' => 'III/b',
                'tmt' => '2011-01-01',
                'status' => 'Aktif'
            ],
            [
                'school_id' => null,
                'full_name' => 'Rizky Ramadhan',
                'nip_nik' => '199801012010012002',
                'nuptk' => '199801012010012002',
                'birth_place' => 'Medan',
                'birth_date' => '1998-02-01',
                'gender' => 'Laki-laki',
                'religion' => 'Islam',
                'address' => 'Jl. Sisingamangaraja No. 13, Pematang Siantar',
                'staff_type' => 'Keamanan',
                'position' => 'Satpam',
                'education_level' => 'SMA/SMK',
                'education_major' => 'IPS',
                'employment_status' => 'Honorer',
                'rank' => null,
                'tmt' => '2012-01-01',
                'status' => 'Aktif'
            ],
            [
                'school_id' => null,
                'full_name' => 'Dewi Sartika',
                'nip_nik' => '199901012010012003',
                'nuptk' => '199901012010012003',
                'birth_place' => 'Pematang Siantar',
                'birth_date' => '1999-03-01',
                'gender' => 'Perempuan',
                'religion' => 'Islam',
                'address' => 'Jl. Sisingamangaraja No. 14, Pematang Siantar',
                'staff_type' => 'Kebersihan',
                'position' => 'Petugas Kebersihan',
                'education_level' => 'SMA/SMK',
                'education_major' => 'IPA',
                'employment_status' => 'Honorer',
                'rank' => null,
                'tmt' => '2013-01-01',
                'status' => 'Aktif'
            ],
            [
                'school_id' => null,
                'full_name' => 'Andi Wijaya',
                'nip_nik' => '200001012010012004',
                'nuptk' => '200001012010012004',
                'birth_place' => 'Medan',
                'birth_date' => '2000-04-01',
                'gender' => 'Laki-laki',
                'religion' => 'Islam',
                'address' => 'Jl. Sisingamangaraja No. 15, Pematang Siantar',
                'staff_type' => 'Keamanan',
                'position' => 'Satpam',
                'education_level' => 'SMA/SMK',
                'education_major' => 'IPS',
                'employment_status' => 'Honorer',
                'rank' => null,
                'tmt' => '2012-01-01',
                'status' => 'Aktif'
            ],
            [
                'school_id' => null,
                'full_name' => 'Yuliana Sari',
                'nip_nik' => '200101012010011001',
                'nuptk' => '200101012010011001',
                'birth_place' => 'Pematang Siantar',
                'birth_date' => '2001-01-01',
                'gender' => 'Perempuan',
                'religion' => 'Kristen',
                'address' => 'Jl. Diponegoro No. 22, Pematang Siantar',
                'staff_type' => 'Tata Usaha',
                'position' => 'Staf TU',
                'education_level' => 'S1',
                'education_major' => 'Administrasi Pendidikan',
                'employment_status' => 'PNS',
                'rank' => 'III/b',
                'tmt' => '2011-01-01',
                'status' => 'Aktif'
            ],
            [
                'school_id' => null,
                'full_name' => 'Rudi Hartono',
                'nip_nik' => '200201012010011002',
                'nuptk' => '200201012010011002',
                'birth_place' => 'Medan',
                'birth_date' => '2002-02-01',
                'gender' => 'Laki-laki',
                'religion' => 'Kristen',
                'address' => 'Jl. Diponegoro No. 23, Pematang Siantar',
                'staff_type' => 'Keamanan',
                'position' => 'Satpam',
                'education_level' => 'SMA/SMK',
                'education_major' => 'IPS',
                'employment_status' => 'Honorer',
                'rank' => null,
                'tmt' => '2012-01-01',
                'status' => 'Aktif'
            ],
            [
                'school_id' => null,
                'full_name' => 'Dewi Anggraini',
                'nip_nik' => '200301012010011003',
                'nuptk' => '200301012010011003',
                'birth_place' => 'Pematang Siantar',
                'birth_date' => '2003-03-01',
                'gender' => 'Perempuan',
                'religion' => 'Kristen',
                'address' => 'Jl. Diponegoro No. 24, Pematang Siantar',
                'staff_type' => 'Kebersihan',
                'position' => 'Petugas Kebersihan',
                'education_level' => 'SMA/SMK',
                'education_major' => 'IPA',
                'employment_status' => 'Honorer',
                'rank' => null,
                'tmt' => '2013-01-01',
                'status' => 'Aktif'
            ],
            [
                'school_id' => null,
                'full_name' => 'Andi Simanjuntak',
                'nip_nik' => '200401012010011004',
                'nuptk' => '200401012010011004',
                'birth_place' => 'Medan',
                'birth_date' => '2004-04-01',
                'gender' => 'Laki-laki',
                'religion' => 'Kristen',
                'address' => 'Jl. Diponegoro No. 25, Pematang Siantar',
                'staff_type' => 'Keamanan',
                'position' => 'Satpam',
                'education_level' => 'SMA/SMK',
                'education_major' => 'IPS',
                'employment_status' => 'Honorer',
                'rank' => null,
                'tmt' => '2012-01-01',
                'status' => 'Aktif'
            ],
            [
                'school_id' => null,
                'full_name' => 'Pardamean Siregar',
                'nip_nik' => '200501012010011001',
                'nuptk' => '200501012010011001',
                'birth_place' => 'Pematang Siantar',
                'birth_date' => '2005-01-01',
                'gender' => 'Laki-laki',
                'religion' => 'Kristen',
                'address' => 'Jl. Melanthon Siregar No. 30, Pematang Siantar',
                'staff_type' => 'Tata Usaha',
                'position' => 'Staf TU',
                'education_level' => 'S1',
                'education_major' => 'Administrasi Pendidikan',
                'employment_status' => 'PNS',
                'rank' => 'III/b',
                'tmt' => '2011-01-01',
                'status' => 'Aktif'
            ],
            [
                'school_id' => null,
                'full_name' => 'Yohana Simbolon',
                'nip_nik' => '200601012010011002',
                'nuptk' => '200601012010011002',
                'birth_place' => 'Medan',
                'birth_date' => '2006-02-01',
                'gender' => 'Perempuan',
                'religion' => 'Kristen',
                'address' => 'Jl. Melanthon Siregar No. 31, Pematang Siantar',
                'staff_type' => 'Keamanan',
                'position' => 'Satpam',
                'education_level' => 'SMA/SMK',
                'education_major' => 'IPS',
                'employment_status' => 'Honorer',
                'rank' => null,
                'tmt' => '2012-01-01',
                'status' => 'Aktif'
            ],
            [
                'school_id' => null,
                'full_name' => 'Rina Simanjuntak',
                'nip_nik' => '200701012010011003',
                'nuptk' => '200701012010011003',
                'birth_place' => 'Pematang Siantar',
                'birth_date' => '2007-03-01',
                'gender' => 'Perempuan',
                'religion' => 'Kristen',
                'address' => 'Jl. Melanthon Siregar No. 32, Pematang Siantar',
                'staff_type' => 'Kebersihan',
                'position' => 'Petugas Kebersihan',
                'education_level' => 'SMA/SMK',
                'education_major' => 'IPA',
                'employment_status' => 'Honorer',
                'rank' => null,
                'tmt' => '2013-01-01',
                'status' => 'Aktif'
            ]
        ];

        foreach ($staffs as $staff) {
            $staff['school_id'] = $schools[array_rand($schools)];
            NonTeachingStaff::create($staff);
        }
    }
}
