<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Student;

class StudentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Membuat 28 siswa manual, didistribusikan ke 9 sekolah
     */
    public function run(): void
    {
        $students = [
            // SD Negeri 122 (ID: 1) - 5 siswa
            [
                'school_id' => 1,
                'full_name' => 'Budi Santoso',
                'nisn' => '1234567001',
                'nis' => '2024001',
                'birth_place' => 'Pematang Siantar',
                'birth_date' => '2014-01-01',
                'gender' => 'Laki-laki',
                'religion' => 'Islam',
                'grade_level' => '6A',
                'major' => null,
                'achievements' => 'Juara 1 Lomba Matematika SD 2023',
                'student_status' => 'Tamat',
                'graduation_status' => 'Lulus',
                'academic_year' => '2024/2025'
            ],
            [
                'school_id' => 1,
                'full_name' => 'Siti Aisyah',
                'nisn' => '1234567002',
                'nis' => '2024002',
                'birth_place' => 'Medan',
                'birth_date' => '2014-02-15',
                'gender' => 'Perempuan',
                'religion' => 'Islam',
                'grade_level' => '6A',
                'major' => null,
                'achievements' => null,
                'student_status' => 'Aktif',
                'graduation_status' => null,
                'academic_year' => '2024/2025'
            ],
            [
                'school_id' => 1,
                'full_name' => 'Rizky Pratama',
                'nisn' => '1234567003',
                'nis' => '2024003',
                'birth_place' => 'Pematang Siantar',
                'birth_date' => '2014-03-10',
                'gender' => 'Laki-laki',
                'religion' => 'Islam',
                'grade_level' => '6B',
                'major' => null,
                'achievements' => 'Juara 2 Lomba IPA SD 2023',
                'student_status' => 'Aktif',
                'graduation_status' => null,
                'academic_year' => '2024/2025'
            ],
            [
                'school_id' => 1,
                'full_name' => 'Dewi Lestari',
                'nisn' => '1234567004',
                'nis' => '2024004',
                'birth_place' => 'Medan',
                'birth_date' => '2014-04-20',
                'gender' => 'Perempuan',
                'religion' => 'Islam',
                'grade_level' => '6B',
                'major' => null,
                'achievements' => null,
                'student_status' => 'Aktif',
                'graduation_status' => null,
                'academic_year' => '2024/2025'
            ],
            [
                'school_id' => 1,
                'full_name' => 'Andi Saputra',
                'nisn' => '1234567005',
                'nis' => '2024005',
                'birth_place' => 'Pematang Siantar',
                'birth_date' => '2014-05-25',
                'gender' => 'Laki-laki',
                'religion' => 'Islam',
                'grade_level' => '6C',
                'major' => null,
                'achievements' => null,
                'student_status' => 'Aktif',
                'graduation_status' => null,
                'academic_year' => '2024/2025'
            ],
            // SMP Negeri 1 (ID: 2) - 5 siswa
            [
                'school_id' => 2,
                'full_name' => 'Ahmad Rizki',
                'nisn' => '1234567006',
                'nis' => '2024006',
                'birth_place' => 'Pematang Siantar',
                'birth_date' => '2011-03-20',
                'gender' => 'Laki-laki',
                'religion' => 'Islam',
                'grade_level' => '9A',
                'major' => null,
                'achievements' => 'Juara 2 Olimpiade IPA SMP 2023',
                'student_status' => 'Tamat',
                'graduation_status' => 'Lulus',
                'academic_year' => '2024/2025'
            ],
            [
                'school_id' => 2,
                'full_name' => 'Putri Rahmawati',
                'nisn' => '1234567007',
                'nis' => '2024007',
                'birth_place' => 'Medan',
                'birth_date' => '2011-04-10',
                'gender' => 'Perempuan',
                'religion' => 'Islam',
                'grade_level' => '9A',
                'major' => null,
                'achievements' => null,
                'student_status' => 'Aktif',
                'graduation_status' => null,
                'academic_year' => '2024/2025'
            ],
            [
                'school_id' => 2,
                'full_name' => 'Dian Pratiwi',
                'nisn' => '1234567008',
                'nis' => '2024008',
                'birth_place' => 'Pematang Siantar',
                'birth_date' => '2011-05-15',
                'gender' => 'Perempuan',
                'religion' => 'Islam',
                'grade_level' => '9B',
                'major' => null,
                'achievements' => 'Juara 1 Lomba Bahasa Inggris SMP 2023',
                'student_status' => 'Aktif',
                'graduation_status' => null,
                'academic_year' => '2024/2025'
            ],
            [
                'school_id' => 2,
                'full_name' => 'Rizal Maulana',
                'nisn' => '1234567009',
                'nis' => '2024009',
                'birth_place' => 'Medan',
                'birth_date' => '2011-06-10',
                'gender' => 'Laki-laki',
                'religion' => 'Islam',
                'grade_level' => '9B',
                'major' => null,
                'achievements' => null,
                'student_status' => 'Aktif',
                'graduation_status' => null,
                'academic_year' => '2024/2025'
            ],
            [
                'school_id' => 2,
                'full_name' => 'Nina Kartika',
                'nisn' => '1234567010',
                'nis' => '2024010',
                'birth_place' => 'Pematang Siantar',
                'birth_date' => '2011-07-05',
                'gender' => 'Perempuan',
                'religion' => 'Islam',
                'grade_level' => '9C',
                'major' => null,
                'achievements' => null,
                'student_status' => 'Aktif',
                'graduation_status' => null,
                'academic_year' => '2024/2025'
            ],
            // SMA Negeri 1 (ID: 3) - 4 siswa
            [
                'school_id' => 3,
                'full_name' => 'Muhammad Farhan',
                'nisn' => '1234567011',
                'nis' => '2024011',
                'birth_place' => 'Pematang Siantar',
                'birth_date' => '2008-05-25',
                'gender' => 'Laki-laki',
                'religion' => 'Islam',
                'grade_level' => '12 IPA 1',
                'major' => 'IPA',
                'achievements' => 'Juara 1 Olimpiade Fisika SMA 2023',
                'student_status' => 'Aktif',
                'graduation_status' => null,
                'academic_year' => '2024/2025'
            ],
            [
                'school_id' => 3,
                'full_name' => 'Annisa Putri',
                'nisn' => '1234567012',
                'nis' => '2024012',
                'birth_place' => 'Medan',
                'birth_date' => '2008-06-15',
                'gender' => 'Perempuan',
                'religion' => 'Islam',
                'grade_level' => '12 IPA 1',
                'major' => 'IPA',
                'achievements' => null,
                'student_status' => 'Aktif',
                'graduation_status' => null,
                'academic_year' => '2024/2025'
            ],
            [
                'school_id' => 3,
                'full_name' => 'Rina Sari',
                'nisn' => '1234567013',
                'nis' => '2024013',
                'birth_place' => 'Pematang Siantar',
                'birth_date' => '2008-07-10',
                'gender' => 'Perempuan',
                'religion' => 'Islam',
                'grade_level' => '12 IPA 2',
                'major' => 'IPA',
                'achievements' => 'Juara 2 Olimpiade Kimia SMA 2023',
                'student_status' => 'Aktif',
                'graduation_status' => null,
                'academic_year' => '2024/2025'
            ],
            [
                'school_id' => 3,
                'full_name' => 'Dimas Prakoso',
                'nisn' => '1234567014',
                'nis' => '2024014',
                'birth_place' => 'Medan',
                'birth_date' => '2008-08-05',
                'gender' => 'Laki-laki',
                'religion' => 'Islam',
                'grade_level' => '12 IPA 2',
                'major' => 'IPA',
                'achievements' => null,
                'student_status' => 'Aktif',
                'graduation_status' => null,
                'academic_year' => '2024/2025'
            ],
            // SD Swasta Budi Mulia (ID: 4) - 4 siswa
            [
                'school_id' => 4,
                'full_name' => 'Lina Marlina',
                'nisn' => '1234567015',
                'nis' => '2024015',
                'birth_place' => 'Pematang Siantar',
                'birth_date' => '2014-06-10',
                'gender' => 'Perempuan',
                'religion' => 'Islam',
                'grade_level' => '6A',
                'major' => null,
                'achievements' => 'Juara 1 Lomba Sains SD 2023',
                'student_status' => 'Aktif',
                'graduation_status' => null,
                'academic_year' => '2024/2025'
            ],
            [
                'school_id' => 4,
                'full_name' => 'Rizky Ramadhan',
                'nisn' => '1234567016',
                'nis' => '2024016',
                'birth_place' => 'Medan',
                'birth_date' => '2014-07-15',
                'gender' => 'Laki-laki',
                'religion' => 'Islam',
                'grade_level' => '6A',
                'major' => null,
                'achievements' => null,
                'student_status' => 'Aktif',
                'graduation_status' => null,
                'academic_year' => '2024/2025'
            ],
            [
                'school_id' => 4,
                'full_name' => 'Dewi Sartika',
                'nisn' => '1234567017',
                'nis' => '2024017',
                'birth_place' => 'Pematang Siantar',
                'birth_date' => '2014-08-20',
                'gender' => 'Perempuan',
                'religion' => 'Islam',
                'grade_level' => '6B',
                'major' => null,
                'achievements' => null,
                'student_status' => 'Aktif',
                'graduation_status' => null,
                'academic_year' => '2024/2025'
            ],
            [
                'school_id' => 4,
                'full_name' => 'Andi Wijaya',
                'nisn' => '1234567018',
                'nis' => '2024018',
                'birth_place' => 'Medan',
                'birth_date' => '2014-09-25',
                'gender' => 'Laki-laki',
                'religion' => 'Islam',
                'grade_level' => '6B',
                'major' => null,
                'achievements' => null,
                'student_status' => 'Aktif',
                'graduation_status' => null,
                'academic_year' => '2024/2025'
            ],
            // SMP Swasta Methodist (ID: 5) - 4 siswa
            [
                'school_id' => 5,
                'full_name' => 'Yuliana Sari',
                'nisn' => '1234567019',
                'nis' => '2024019',
                'birth_place' => 'Pematang Siantar',
                'birth_date' => '2011-08-10',
                'gender' => 'Perempuan',
                'religion' => 'Kristen',
                'grade_level' => '9A',
                'major' => null,
                'achievements' => 'Juara 1 Lomba Bahasa Inggris SMP 2023',
                'student_status' => 'Aktif',
                'graduation_status' => null,
                'academic_year' => '2024/2025'
            ],
            [
                'school_id' => 5,
                'full_name' => 'Rudi Hartono',
                'nisn' => '1234567020',
                'nis' => '2024020',
                'birth_place' => 'Medan',
                'birth_date' => '2011-09-15',
                'gender' => 'Laki-laki',
                'religion' => 'Kristen',
                'grade_level' => '9A',
                'major' => null,
                'achievements' => null,
                'student_status' => 'Aktif',
                'graduation_status' => null,
                'academic_year' => '2024/2025'
            ],
            [
                'school_id' => 5,
                'full_name' => 'Dewi Anggraini',
                'nisn' => '1234567021',
                'nis' => '2024021',
                'birth_place' => 'Pematang Siantar',
                'birth_date' => '2011-10-20',
                'gender' => 'Perempuan',
                'religion' => 'Kristen',
                'grade_level' => '9B',
                'major' => null,
                'achievements' => null,
                'student_status' => 'Aktif',
                'graduation_status' => null,
                'academic_year' => '2024/2025'
            ],
            [
                'school_id' => 5,
                'full_name' => 'Andi Simanjuntak',
                'nisn' => '1234567022',
                'nis' => '2024022',
                'birth_place' => 'Medan',
                'birth_date' => '2011-11-25',
                'gender' => 'Laki-laki',
                'religion' => 'Kristen',
                'grade_level' => '9B',
                'major' => null,
                'achievements' => null,
                'student_status' => 'Aktif',
                'graduation_status' => null,
                'academic_year' => '2024/2025'
            ],
            // SMA Swasta HKBP (ID: 6) - 3 siswa
            [
                'school_id' => 6,
                'full_name' => 'Pardamean Siregar',
                'nisn' => '1234567023',
                'nis' => '2024023',
                'birth_place' => 'Pematang Siantar',
                'birth_date' => '2008-09-10',
                'gender' => 'Laki-laki',
                'religion' => 'Kristen',
                'grade_level' => '12 IPA 1',
                'major' => 'IPA',
                'achievements' => 'Juara 1 Olimpiade Fisika SMA 2023',
                'student_status' => 'Aktif',
                'graduation_status' => null,
                'academic_year' => '2024/2025'
            ],
            [
                'school_id' => 6,
                'full_name' => 'Yohana Simbolon',
                'nisn' => '1234567024',
                'nis' => '2024024',
                'birth_place' => 'Medan',
                'birth_date' => '2008-10-15',
                'gender' => 'Perempuan',
                'religion' => 'Kristen',
                'grade_level' => '12 IPA 1',
                'major' => 'IPA',
                'achievements' => null,
                'student_status' => 'Aktif',
                'graduation_status' => null,
                'academic_year' => '2024/2025'
            ],
            [
                'school_id' => 6,
                'full_name' => 'Rina Simanjuntak',
                'nisn' => '1234567025',
                'nis' => '2024025',
                'birth_place' => 'Pematang Siantar',
                'birth_date' => '2008-11-20',
                'gender' => 'Perempuan',
                'religion' => 'Kristen',
                'grade_level' => '12 IPA 2',
                'major' => 'IPA',
                'achievements' => null,
                'student_status' => 'Aktif',
                'graduation_status' => null,
                'academic_year' => '2024/2025'
            ],
            // SMK Negeri 1 (ID: 7) - 1 siswa
            [
                'school_id' => 7,
                'full_name' => 'Bayu Nugroho',
                'nisn' => '1234567026',
                'nis' => '2024026',
                'birth_place' => 'Pematang Siantar',
                'birth_date' => '2008-12-10',
                'gender' => 'Laki-laki',
                'religion' => 'Islam',
                'grade_level' => '12 TKJ 1',
                'major' => 'TKJ',
                'achievements' => 'Juara 1 LKS TKJ Tingkat Provinsi 2023',
                'student_status' => 'Aktif',
                'graduation_status' => null,
                'academic_year' => '2024/2025'
            ],
            // SMK Swasta Teknologi Mandiri (ID: 8) - 1 siswa
            [
                'school_id' => 8,
                'full_name' => 'Sari Indah Pratiwi',
                'nisn' => '1234567027',
                'nis' => '2024027',
                'birth_place' => 'Medan',
                'birth_date' => '2009-01-15',
                'gender' => 'Perempuan',
                'religion' => 'Islam',
                'grade_level' => '12 RPL 1',
                'major' => 'RPL',
                'achievements' => 'Juara 2 Lomba Programming 2023',
                'student_status' => 'Aktif',
                'graduation_status' => null,
                'academic_year' => '2024/2025'
            ],
            // TK Negeri Pembina (ID: 9) - 1 siswa
            [
                'school_id' => 9,
                'full_name' => 'Kirana Aulia',
                'nisn' => '1234567028',
                'nis' => '2024028',
                'birth_place' => 'Pematang Siantar',
                'birth_date' => '2019-03-20',
                'gender' => 'Perempuan',
                'religion' => 'Islam',
                'grade_level' => 'Kelompok B',
                'major' => null,
                'achievements' => 'Juara 1 Lomba Mewarnai TK 2023',
                'student_status' => 'Aktif',
                'graduation_status' => null,
                'academic_year' => '2024/2025'
            ]
        ];
        foreach ($students as $student) {
            Student::create($student);
        }
    }
}
